view-usage-report: remove "project" field
Problem: The "project" field is mistakenly included in the "fields"
argument when fetching jobs in the view_usage_report() function, which
causes parsing the fields a few lines further fail with the following
ValueError:

ValueError: invalid literal for int() with base 10: '*'

Remove the "project" field from the "fields" argument when fetching
jobs since it is unneeded.